### ISSUE TITLE
Don't store additional creds info for Google shared users

### ISSUE THREAD

**Issue by crspybits** [crspybits/SyncServerII#13]
Currently, I'm storing additional auth token information for all Google users in the mySQL database. However, this isn't necessary for Google users and provides a potential security issue. E.g., if the database was hacked.

**Comment by danligas** [comment]
Could the auth token be limited to a specific portion of the cloud storage? A folder, for example.

**Comment by crspybits** [comment]
@danligas I think you are talking about a somewhat different issue. Here, my concern is that a purely sharing user need not have detailed credential information stored in the mySQL database. There's no point. This cred info is only used to read/write data into Google Drive. For a purely sharing user that doesn't happen. 

I think the point where your comment would apply is when, for an owning user when we wanted to limit the access we had to their data. I do like that idea and shall have to investigate it.
