### ISSUE TITLE
Supporting "conversation" themed apps and allowing files from multiple cloud storage clients

### ISSUE THREAD

**Issue by crspybits** [crspybits/SyncServerII#18]
This is a broad idea, in need of further refinement.

Currently, the concept with SyncServer is that a single cloud storage (owning) user can share their data with multiple other (sharing) users. What if multiple users could contribute files from their cloud storage in some kind of "conversation" themed application(s). E.g., with SharedImages, multiple participants might contribute images and have their images stored in their own Google Drive (or Dropbox etc). This could still allow for users that didn't own cloud storage-- e.g., Facebook users.

Note that this would not necessarily be suited to all applications. Some applications might not make use of a "conversation" type theme were this would be appropriate. Or they might just use SyncServer for backup purposes.

**Comment by danligas** [comment]
The idea is the library would abstract the underlying storage of the objects

**Comment by crspybits** [comment]
Nodding. In this concept the data would be fragmented across multiple cloud storage locations. E.g., for SharedImages, some files in my Google Drive, some files in your Dropbox etc. Would it ever be useful to (perhaps at the user's option) to store *all* files on your cloud storage. This would be redundant but would give you a copy of everything.

**Comment by danligas** [comment]
In a tangent, the "ownership" of a file could be transferred and would be
the responsibility of the receiving owner to make a copy of the file. The
releaser would clean up afterwards by delete their copy.

On Mon, Aug 7, 2017 at 8:57 PM, Christopher Prince <notifications@github.com

**Comment by crspybits** [comment]
Lots of possibilities here! It's pretty cool Dany! 

It seems like what I'm doing so far can be considered a subset of what this concept entails. Let me try to make that clear.

One thing that will be necessary for this fragmented cloud storage system is a policy decision about where to store files-- at least when a user doesn't have any cloud storage. Let's say Rod and Dany are sharing files, each having a cloud storage account (say, Google Drive). They invite Chris, who wants to connect using Facebook. Chris doesn't have any cloud storage. Now, Chris uploads a file. Where does it get stored? In Dany's or Rod's storage? This is the policy decision I'm thinking about.

And the picture gets broader. Generally, when someone uploads a file a decision needs to be made about where the data gets stored. It could be stored in their cloud storage (if they own some) or someone elses. One could imagine limits imposed by the owners of the account. If we assume that somehow files could get corrupted, then we could also store redundant copies of the same file in different people's cloud storage (perhaps preferring different types of cloud storage for extra safety).

This resembles the current approach with SyncServer as currently implemented in the sense that I've made a specific policy decision: All files get stored in a single cloud storage account.

**Comment by crspybits** [comment]
This policy decision probably can't be made purely by the system. You'd have to ask the cloud storage owning user some kind of question. The simplest question would be something like: "Store some files in your cloud storage, or store no files in your cloud storage?". If they say "store some" then getting a more complicated response seems more difficult. What we might want is an amount E.g., give them a slider from 1MB to 1GB. I'm not sure how well people might make such a choice tho.

**Comment by danligas** [comment]
There may be auth accounts that do not have cloud storage capability,
however, Facebook is not one of them. With a security token, you can create
an album with APIs and store files which in turn can be shared with URLs. I
have an example that I will share. (This was a web app that I created to
show slides in my Kitchen TV frame).
