### ISSUE TITLE
Make automated AWS installation procedure for installing SyncServer

### ISSUE THREAD

**Issue by crspybits** [crspybits/SyncServerII#33]
I'd like a means to start from a blank EC2 instance and install the server. It seems this is something that could be done with Docker. I'd like this to be independent of AWS-- i.e., so I could do this on some other server system. Such as my home Linux 16.04 VM.

A main reason to do this is to quickly start up a staging or development server, to test out changes planned for release. (And then, shut that server down after the testing was complete, so I didn't have to keep paying for it).

**Comment by danligas** [comment]
Docker containers are defined here:
https://docs.docker.com/get-started/part2/#dockerfile

**Comment by crspybits** [comment]
Dany says to use:
FROM  swiftdocker/swift

**Comment by crspybits** [comment]
Pricing model on AWS: We're thinking of using several Docker containers. Can we do this all within a single EC2 instance?

**Comment by danligas** [comment]
aws configure 
AWS Access Key ID [None]: AKIAI44QH8DHBEXAMPLE (from above step)
AWS Secret Access Key [None]: je7MtGbClwBF/2Zp (from above step)
Default region name [None]: us-east-1 (east is the best)
Default output format [None]: json (is there any other way to communicate?)

aws ec2 create-security-group            --group-name dev-sg --description "security group for home development environment in EC2"
# below line can restrict to home ip address or 0.0.0.0/0 for unlimited
aws ec2 authorize-security-group-ingress --group-name dev-sg --protocol tcp --port 22 --cidr `dig +short myip.opendns.com @resolver1.opendns.com`/32

aws ec2 create-key-pair --key-name dev-key --query 'KeyMaterial' --output text > dev_key.pem
chmod 400 dev_key.pem

# ubuntu 16.04 image, name it dev01
aws ec2 run-instances --image-id ami-10547475 --security-groups dev-sg --count 1 --instance-type t2.micro --key-name dev-key --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=dev01}]" --query 'Instances[0].InstanceId' > dev01_instanceId

# get public dns entry of new instance
aws ec2 describe-instances --instance-ids `cat dev01_instanceId | sed -e 's/"//g'` --query 'Reservations[0].Instances[0].PublicDnsName' | sed -e 's/"//g' > dev01_dns

# have a handy go file
echo ssh -i dev_key.pem ubuntu@`cat dev01_dns` > dev01_ssh

. dev01_ssh

# cleanup when done
aws ec2 terminate-instances --instance-ids `cat dev01_instanceId | sed -e 's/"//g'`

**Comment by danligas** [comment]
Now the first part (generating an storing a PEM file) only needs to be done once. I created a parametrized file that lets you build a server and track the important bits (ie. cli-new-ec2 dev01)

cli-new-ec2
`#!/bin/bash`
`# ubuntu 16.04 image, name it ${1}`
`aws ec2 run-instances --image-id ami-10547475 --security-groups dev-sg --count 1 --instance-type t2.micro --key-name dev-key --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${1}}]" --query 'Instances[0].InstanceId' > ${1}_instanceId`

`# get public dns entry of new instance`
`aws ec2 describe-instances --instance-ids `cat ${1}_instanceId | sed -e 's/"//g'` --query 'Reservations[0].Instances[0].PublicDnsName' | sed -e 's/"//g' > ${1}_dns`

`# have a handy go file`
`echo ssh -i dev_key.pem ubuntu@``cat ${1}_dns`` > ${1}_ssh`

**Comment by danligas** [comment]
[cli-new-ec2.txt](https://github.com/crspybits/SyncServerII/files/1327565/cli-new-ec2.txt)
[cli-setup.txt](https://github.com/crspybits/SyncServerII/files/1327563/cli-setup.txt)
[docker-compose.yml.txt](https://github.com/crspybits/SyncServerII/files/1327566/docker-compose.yml.txt)
[install_docker.txt](https://github.com/crspybits/SyncServerII/files/1327567/install_docker.txt)
[ss_notes.txt](https://github.com/crspybits/SyncServerII/files/1327564/ss_notes.txt)
[all.zip](https://github.com/crspybits/SyncServerII/files/1327569/all.zip)

Ok, so I tried uploading each file, but it did not like the extension. I uploaded each file with a fake .txt which needs to be removed, or a zip file which when unziped has all the files named correctly.

So far we have used cli-setup (run individual commands as needed), and discussed cli-new-ec2 to run as a command.

Now once the base VM is running, we add Docker to it so we can create our containers needed.

`. install_docker`

This will leave you with a command prompt inside the app container. You can travel to root folder and you should see your source code. Deal with Server.json and ServerTest.json and run your test.

Let me know how it goes.

**Comment by crspybits** [comment]
After running install_docker:

when you are in the /root folder of the VM
first command you run is 
docker-compose up -d
so that the two containers get created and started
you can verify they are running  with
docker ps -a

**Comment by danligas** [comment]
I'm reading there is a free tier here that never expires:
https://cloud.google.com/compute/pricing
