### ISSUE TITLE
Old image migration

### ISSUE THREAD

**Issue by crspybits** [crspybits/SyncServerII#65]
Dany: Chris, I changed my mind. Please do a mass update on existing pictures so we can comment on them. If I delete and re upload, I'll end up changing the order the images are in. I am spacial in nature and changing the order would mess up my experience.

**Comment by crspybits** [comment]
There's another related issue in here: If there are lots of images being shared, how does the user know when an image far out of view has unread comments?

**Comment by danligas** [comment]
I feel sorting options in the future.
