### ISSUE TITLE
DEVOPS: Means to shut down the server temporarily for maintenance

### ISSUE THREAD

**Issue by crspybits** [crspybits/SyncServerII#84]
How to alert end users to this fact? I.e., how to let a client app display a message to the users “Server Down For Maintenance” in this case?
What about: When a client fails on accessing server, it hits a static web page that returns JSON data, which has a message for users when the server is down.
Server can check this same web page when it’s coming to make sure there is no message there-- i.e., if the server is up, should have no static message.
Where to place this info? Need a static web site at a known location. This needs to be easily accessed and edited. Could use an AWS S3 bucket. See https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html
https://stackoverflow.com/questions/11201316/how-to-configure-ssl-for-amazon-s3-bucket

**Comment by crspybits** [comment]
Some ideas: 
https://developer.akamai.com/blog/2017/08/07/how-create-devops-friendly-maintenance-page

**Comment by crspybits** [comment]
Goals:
a) I need to stop use of the server/API so that I can perform database maintenance such as a migration. This might occur together with a new version of the API that makes use of that database migration.

b) I need to stop use of the server/API so that I can release an incompatible version of that API -- but this could be done with a forced app update switch/HTTP key in the new version rolled out.

**Comment by crspybits** [comment]
Also need (a) a change to the iOS client to deal with this, and (b) a change to SharedImages to deal with the change to the client.

**Comment by danligas** [comment]
Consider this mode instead: the database goes into read-only mode. Possibly
with "snapshot" database capabilities. This allows a version of your server
code to continue to run while the database is updated/converted. Once this
maintenance is completed, then the current server version is taken off line
and the new version becomes available. This should occur within seconds and
the client can handle this through a retry-timeout. The client should be
aware the server is in "read-only" mode and act accordingly (probably not
allow uploads, unless queued, allow reading by not writing comments, etc).

**Comment by crspybits** [comment]
Thanks for the idea, Dany. I think it's easier, implementation-wise, to go with strategy I outlined.
